# Java build based on https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
# 
# Create a jar of the project and put it in the release section in github
# 
name: build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  release:
    needs: prep
    runs-on: ubuntu-latest
    env:
      releaseVersion: 1.14.0
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      -
        name: Release
        if: success()
        run: |
          ./gradlew clean release \
            -Prelease.useAutomaticVersion=true \
            -Prelease.releaseVersion=${{ env.releaseVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Archive artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: build/libs/*.jar
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          name: ${{ env.releaseVersion }}
          tag_name: ${{ env.releaseVersion }}
          draft: true
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
